export type Skill='grammar'|'vocabulary'|'reading';
export type Level='A1'|'A2'|'B1'|'B2'|'C1';
export type Item={level:Level;skill:Skill;text?:string;question:string;options:string[];answer:number;why:string};
export const questions:Item[]=[
 {level:'A1',skill:'grammar',question:'My sister ___ a teacher.',options:['are','is','am','be'],answer:1,why:'Use “is” with “my sister”, just as you would with “she”.'},
 {level:'A1',skill:'vocabulary',question:'Which word is a place where you can buy bread?',options:['library','hospital','bakery','station'],answer:2,why:'A bakery sells bread and other baked food.'},
 {level:'A1',skill:'reading',text:'The café opens at 8 a.m. and closes at 4 p.m. It is closed on Sundays.',question:'When can you visit the café?',options:['Sunday at 10 a.m.','Monday at 6 p.m.','Tuesday at 7 a.m.','Wednesday at 11 a.m.'],answer:3,why:'Wednesday at 11 a.m. is within the opening hours and is not a Sunday.'},
 {level:'A1',skill:'grammar',question:'We ___ to school every day.',options:['go','goes','going','is go'],answer:0,why:'Use the base form “go” with “we” in the present simple.'},
 {level:'A2',skill:'grammar',question:'I ___ my friend yesterday.',options:['see','have see','saw','seeing'],answer:2,why:'“Yesterday” refers to the past. The past simple of “see” is “saw”.'},
 {level:'A2',skill:'vocabulary',question:'The blue bag costs £20. The red bag costs £35. The blue bag is ___.',options:['heavier','cheaper','older','faster'],answer:1,why:'“Cheaper” means it costs less money.'},
 {level:'A2',skill:'reading',text:'Hi Sam, the train is delayed. Please meet me outside the station at 6:30 instead of 6. — Jo',question:'What should Sam do?',options:['Meet Jo half an hour later','Wait on the train','Go home at six','Meet Jo at a different station'],answer:0,why:'Jo changes the meeting time from 6 to 6:30, but keeps the same place.'},
 {level:'A2',skill:'grammar',question:'There isn’t ___ milk in the fridge.',options:['many','a','some of','any'],answer:3,why:'“Any” is used in negative statements with uncountable nouns such as milk.'},
 {level:'B1',skill:'grammar',question:'I’ve lived here ___ 2021.',options:['for','during','since','from'],answer:2,why:'Use “since” with the starting point of a period continuing into the present.'},
 {level:'B1',skill:'vocabulary',question:'We had to put off the picnic because of the rain. “Put off” means:',options:['postpone','organise','enjoy','forget permanently'],answer:0,why:'“Put off” means delay something until a later time.'},
 {level:'B1',skill:'reading',text:'The museum is free on Fridays, but you still need to reserve a ticket online. Walk-in visitors may not be admitted when it is busy.',question:'What is the safest way to get in on Friday?',options:['Pay at the door','Arrive without a ticket','Visit only on quiet days','Reserve a free ticket online'],answer:3,why:'Entry is free, but the museum still requires an online reservation.'},
 {level:'B1',skill:'reading',text:'Leah enjoys working from home because she can concentrate. However, she goes to the office twice a week to discuss ideas with colleagues.',question:'Why does Leah still visit the office?',options:['She cannot concentrate at home','She values exchanging ideas in person','She dislikes working alone every day','Her computer only works there'],answer:1,why:'The text explicitly says that she goes in to discuss ideas with colleagues.'},
 {level:'B2',skill:'grammar',question:'If I had known about the delay, I ___ earlier.',options:['would leave','had left','would have left','will have left'],answer:2,why:'An unreal past condition uses “if + past perfect” and “would have + past participle”.'},
 {level:'B2',skill:'vocabulary',question:'The evidence was compelling. It was:',options:['incomplete','convincing','irrelevant','contradictory'],answer:1,why:'“Compelling” evidence is persuasive or convincing.'},
 {level:'B2',skill:'reading',text:'Although the new bus route attracted fewer passengers than expected in its first month, usage has risen steadily since. Officials say it is too early to judge the scheme.',question:'Which conclusion is best supported?',options:['The scheme has definitely failed','Officials plan to cancel the route','Passenger numbers are falling','The initial figures may not reflect the eventual outcome'],answer:3,why:'Rising usage and the officials’ caution suggest that the initial figures are not conclusive.'},
 {level:'B2',skill:'reading',text:'The reviewer praises the film’s performances but argues that its ambitious plot leaves several important questions unresolved.',question:'The reviewer’s opinion is:',options:['mixed: strong acting, but weaknesses in the story','wholly negative','positive about the plot but not the acting','based only on the ending'],answer:0,why:'The reviewer identifies both a strength and a weakness.'},
 {level:'C1',skill:'grammar',question:'Not until the report was published ___ the scale of the problem.',options:['they realised','did they realise','they had realised','had realised they'],answer:1,why:'After an initial negative phrase such as “Not until”, the main clause uses subject–auxiliary inversion.'},
 {level:'C1',skill:'vocabulary',question:'Her agreement was tacit rather than explicit. This means she:',options:['agreed only in writing','openly opposed the proposal','changed her mind repeatedly','implied agreement without stating it directly'],answer:3,why:'“Tacit” means understood or implied without being expressed directly.'},
 {level:'C1',skill:'reading',text:'The proposal’s apparent simplicity is its chief political asset. Yet the administrative burden it shifts to local authorities may ultimately undermine the very efficiencies it promises.',question:'What tension does the writer identify?',options:['Political appeal may conceal practical costs','Local authorities unanimously support the proposal','Administrative complexity makes the proposal popular','The promised efficiencies have already been achieved'],answer:0,why:'The writer contrasts the proposal’s attractive simplicity with potentially damaging implementation costs.'},
 {level:'C1',skill:'reading',text:'The author does not dismiss the findings outright; rather, she questions whether conclusions drawn from such a narrow sample warrant the confidence with which they have been presented.',question:'What is the author primarily challenging?',options:['The existence of the data','The researchers’ intentions','The strength of the claims relative to the evidence','The need for any further research'],answer:2,why:'The concern is whether a limited sample justifies the confidence of the conclusions.'}
];
export const bands:Level[]=['A1','A2','B1','B2','C1'];
export function assess(answers:Record<number,number|null>){
 const total=questions.filter((q,i)=>answers[i]===q.answer).length;
 const bandScores=bands.map(level=>questions.reduce((sum,q,i)=>sum+(q.level===level&&answers[i]===q.answer?1:0),0));
 let highest=-1;for(let i=0;i<bands.length;i++){if(bandScores[i]<3)break;highest=i}
 const level=highest<0?'Pre-A1 / A1':bands[highest];
 const path=highest<=0?'starter':highest===1?'bridge':'private';
 const skills=(['grammar','vocabulary','reading'] as Skill[]).map(skill=>{const items=questions.map((q,i)=>({q,i})).filter(({q})=>q.skill===skill);return {skill,correct:items.filter(({q,i})=>answers[i]===q.answer).length,total:items.length}});
 return {total,bandScores,level,path,skills};
}
