'use client';
import {useEffect,useRef,useState} from 'react';
import {AnimatePresence,motion,useReducedMotion} from 'framer-motion';
import {ArrowRight,Check,ChevronLeft,Headphones,RotateCcw,Volume2,X} from 'lucide-react';
import {Lesson} from './lessons';
import BeePet from './bee-pet';
const stages=['Discover','Listen','Build','Quiz','Speak'];
const sentences=[['Nice','to','meet','you.'],['I','study','English','every','day.'],['I’d','like','a','coffee,','please.'],['There','is','a','small','park.']];
export default function LessonPlayer({lesson,index,close,onComplete,onNext,paused=false}:{lesson:Lesson;index:number;close:()=>void;onComplete:()=>void;onNext?:()=>void;paused?:boolean}){
 const root=useRef<HTMLElement>(null),reduced=useReducedMotion();
 const [step,setStep]=useState(0),[flipped,setFlipped]=useState<number[]>([]),[explored,setExplored]=useState<number[]>([]),[selected,setSelected]=useState<number[]>([]),[checked,setChecked]=useState(false),[q,setQ]=useState(0),[answers,setAnswers]=useState<Record<number,number>>({}),[heard,setHeard]=useState<number[]>([]),[playing,setPlaying]=useState<number|null>(null),[message,setMessage]=useState(''),[writing,setWriting]=useState(''),[keyboard,setKeyboard]=useState(false);
 const duration=reduced||keyboard?0:.25;
 const sentence=sentences[index];const tiles=sentence.map((word,id)=>({word,id}));const mixed=tiles.length===4?[tiles[2],tiles[0],tiles[3],tiles[1]]:[tiles[3],tiles[1],tiles[4],tiles[0],tiles[2]];
 const correct=selected.length===sentence.length&&selected.every((id,i)=>id===i);
 const score=lesson.questions.filter((question,i)=>answers[i]===question.answer).length;
 useEffect(()=>{const previous=document.activeElement as HTMLElement; const overflow=document.body.style.overflow;document.body.style.overflow='hidden'; root.current?.querySelector<HTMLElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='Tab'){const nodes=root.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a,textarea');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(!root.current?.contains(document.activeElement)){e.preventDefault();first.focus();return}if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=overflow;window.speechSynthesis?.cancel();previous?.focus()}},[close]);
 const go=(n:number)=>{window.speechSynthesis?.cancel();setPlaying(null);setStep(n);root.current?.scrollTo({top:0,behavior:'instant'})};
 const speak=(text:string,id:number)=>{if(!window.speechSynthesis){setMessage('Audio isn’t available here. Read the words aloud to practise.');return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.8;setPlaying(id);u.onend=()=>setPlaying(null);u.onerror=()=>{setPlaying(null);setMessage('Your browser could not play this audio. Try again or read the line aloud.')};window.speechSynthesis.speak(u);setMessage('Audio uses your device’s English voice.');};
 const finish=()=>{onComplete();go(5)};
 return <motion.div className="lesson-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration}}><motion.section ref={root} role="dialog" aria-modal="true" aria-labelledby="lesson-title" className="lesson-dialog immersive" initial={{scale:.96,opacity:0}} animate={{scale:1,opacity:1}} exit={{scale:.96,opacity:0}} transition={{duration}} onPointerDownCapture={()=>setKeyboard(false)} onKeyDownCapture={()=>setKeyboard(true)}>
 <div className="dialog-header"><span>A1 STARTER <b> / </b> LESSON 0{index+1}</span><button onClick={close} aria-label="Close lesson"><X size={21}/></button></div><div className="player-title"><div><p className="eyebrow">{lesson.topic}</p><h2 id="lesson-title">{lesson.title}</h2></div><div className={`player-motif ${lesson.color}`}>{lesson.icon}</div></div>
 {step<5&&<><div className="journey-track"><motion.i style={{transformOrigin:'left'}} animate={{scaleX:(step+1)/5}} transition={{duration}}/></div><nav className="player-steps" aria-label="Lesson steps">{stages.map((name,i)=><button key={name} className={step===i?'current':step>i?'visited':''} aria-current={step===i?'step':undefined} onClick={()=>go(i)}><span>{step>i?<Check size={12}/>:i+1}</span>{name}</button>)}</nav><div className="teacher-tip"><span className="author-avatar" role="img" aria-label="BeeLikeNative creator"/><p><strong>A little encouragement</strong>{['Tap a card. Discover a word. Try it out loud.','Hear it once. Say it once. Make it yours.','Put the words together, one little piece at a time.','Mistakes help you learn. You can always try again.','Now use your own words. Small sentences count.'][step]}</p><BeePet compact paused={paused} completed={score}/></div></>}
 <AnimatePresence mode="wait"><motion.div key={step} className="step-content interactive-content" initial={{opacity:0,x:keyboard?0:12}} animate={{opacity:1,x:0}} exit={{opacity:0,x:keyboard?0:-12}} transition={{duration}}>
 {step===0&&<><h3>Words worth knowing.</h3><p>Tap each card to discover its meaning.</p><div className="flashcard-grid">{lesson.words.map(([word,meaning],i)=><div className="flashcard-wrap" key={word}><motion.button className={`flashcard ${lesson.color}`} aria-label={`${word}: ${flipped.includes(i)?meaning:'tap to reveal meaning'}`} aria-pressed={flipped.includes(i)} animate={{rotateY:flipped.includes(i)?180:0}} transition={{duration:duration===0?0:.4}} onClick={()=>{setExplored([...new Set([...explored,i])]);setFlipped(flipped.includes(i)?flipped.filter(n=>n!==i):[...flipped,i])}}><span className="flashcard-face" aria-hidden={flipped.includes(i)}><small>WORD 0{i+1}</small><strong>{word}</strong><span>Tap to discover <span>↻</span></span></span><span className="flashcard-face back" aria-hidden={!flipped.includes(i)}><small>IT MEANS…</small><strong>{meaning}</strong><span>Tap to see the word ↻</span></span></motion.button><button className="word-audio" onClick={()=>speak(word,100+i)} aria-label={`Listen to ${word}`}><Volume2 size={15}/>{playing===100+i?'Listening…':'Hear it'}</button></div>)}</div><div className="discovery-count"><Check size={14}/>{explored.length} of {lesson.words.length} words explored</div><details className="grammar-note"><summary>The tiny grammar guide <span>+</span></summary><p>{lesson.rule}</p><blockquote>{lesson.example}</blockquote></details></>}
 {step===1&&<><h3>A conversation, one line at a time.</h3><p>Tap a line to hear it. Say it back before moving on.</p>{lesson.videoUrl&&<video controls preload="metadata" className="lesson-video"><source src={lesson.videoUrl}/>{lesson.captionsUrl&&<track kind="captions" src={lesson.captionsUrl} srcLang="en" label="English" default/>}</video>}<div className="conversation-lines">{lesson.dialogue.map((line,i)=>{const [speaker,...rest]=line.split(':');return <motion.button key={line} className={`${i%2?'reply':''} ${playing===i?'speaking':''}`} whileTap={{scale:.98}} onClick={()=>{speak(rest.join(':').trim(),i);setHeard([...new Set([...heard,i])])}}><span className="speaker-avatar">{speaker.trim().charAt(0)}</span><span><small>{speaker}</small><strong>{rest.join(':').trim()}</strong></span><span className="line-sound">{playing===i?<span className="sound-bars"><i/><i/><i/></span>:heard.includes(i)?<Check size={17}/>:<Volume2 size={17}/>}</span></motion.button>})}</div><div className="listening-bottom"><span>{heard.length} / {lesson.dialogue.length} lines explored</span><button onClick={()=>{window.speechSynthesis?.cancel();setPlaying(null)}}><X size={14}/> Stop audio</button></div></>}
 {step===2&&<><h3>Build a little conversation.</h3><p>Tap the words in the right order. Tap a placed word to take it back.</p><div className={`sentence-board ${checked?(correct?'solved':'retry'):''}`} aria-label="Your sentence"><AnimatePresence>{selected.map((id,i)=><motion.button key={id} initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.9}} transition={{duration}} onClick={()=>{setSelected(selected.filter(n=>n!==id));setChecked(false)}} aria-label={`Remove ${sentence[id]}`}><small>{i+1}</small>{sentence[id]}</motion.button>)}</AnimatePresence>{selected.length===0&&<span>Your sentence goes here…</span>}</div><div className="word-bank">{mixed.map(({word,id})=><motion.button key={id} whileTap={{scale:.93}} disabled={selected.includes(id)} onClick={()=>{setSelected([...selected,id]);setChecked(false)}}>{word}<span>+</span></motion.button>)}</div><div className="builder-controls"><button className="reset-link" onClick={()=>{setSelected([]);setChecked(false)}}><RotateCcw size={14}/> Start again</button><button className="button dark" disabled={selected.length!==sentence.length} onClick={()=>setChecked(true)}>Check my sentence <Check size={16}/></button></div><AnimatePresence>{checked&&<motion.div className={`activity-feedback ${correct?'success':'try-again'}`} role="status" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration}}><strong>{correct?'✦ You put it together!':'Almost! Try a different order.'}</strong><p>{correct?'Now say your sentence out loud.':`Hint: start with “${sentence[0]}”.`}</p>{correct&&<button onClick={()=>speak(sentence.join(' '),200)}><Volume2 size={15}/> Hear your sentence</button>}</motion.div>}</AnimatePresence></>}
 {step===3&&<><div className="quiz-heading"><h3>A little confidence check.</h3><span>{score} / 3 correct</span></div><div className="quiz-dots">{lesson.questions.map((question,i)=><span className={i===q?'now':answers[i]===question.answer?'right':answers[i]!==undefined?'wrong':''} key={i}/>)}</div><AnimatePresence mode="wait"><motion.fieldset key={q} className="quiz-question" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration}}><legend><small>QUESTION {q+1} OF 3</small>{lesson.questions[q].q}</legend><div className="quiz-options">{lesson.questions[q].options.map((option,i)=><motion.button key={option} whileTap={{scale:.99}} className={answers[q]===i?(i===lesson.questions[q].answer?'correct':'incorrect'):''} aria-pressed={answers[q]===i} onClick={()=>setAnswers({...answers,[q]:i})}><span>{String.fromCharCode(65+i)}</span>{option}{answers[q]===i&&i===lesson.questions[q].answer&&<Check size={18}/>}</motion.button>)}</div>{answers[q]!==undefined&&<motion.div className={`activity-feedback ${answers[q]===lesson.questions[q].answer?'success':'try-again'}`} role="status" initial={{opacity:0,y:5}} animate={{opacity:1,y:0}} transition={{duration}}><strong>{answers[q]===lesson.questions[q].answer?'That’s it. Nicely done!':'You’re learning. Have another go.'}</strong><p>{lesson.questions[q].why}</p></motion.div>}</motion.fieldset></AnimatePresence><div className="quiz-controls"><button disabled={q===0} className="reset-link" onClick={()=>setQ(q-1)}><ChevronLeft size={15}/> Previous</button><button className="button dark" disabled={answers[q]!==lesson.questions[q].answer} onClick={()=>q<2?setQ(q+1):go(4)}>{q<2?'Next question':'Let’s use your words'}<ArrowRight size={16}/></button></div></>}
 {step===4&&<><h3>Make it your own.</h3><p>{lesson.prompt}</p><label className="writing-label" htmlFor="practice">Try a short sentence. Then say it out loud.</label><textarea id="practice" value={writing} onChange={e=>setWriting(e.target.value)} rows={4} placeholder="Your conversation starts here…"/><div className="writing-meta"><span>{writing.trim()?writing.trim().split(/\s+/).length:0} words · every word is a step</span><button disabled={!writing.trim()} onClick={()=>speak(writing,300)}><Volume2 size={15}/> Hear my words</button></div><p className="micro">Your writing stays in this lesson and is not submitted.</p><div className="speaking-checklist"><p><span>01</span>Read your sentence slowly.</p><p><span>02</span>Look away and try saying it again.</p><p><span>03</span>Try it with a friend—or just to yourself.</p></div><button className="button dark" onClick={finish}>I’ve practised. Finish lesson <Check size={18}/></button></>}
 {step===5&&<div className="completion-scene"><div className="celebration" aria-hidden="true">{Array.from({length:12},(_,i)=><motion.span key={i} className={['yellow','pink','green','blue'][i%4]} initial={{opacity:0,x:0,y:0,scale:0}} animate={{opacity:[0,1,1,0],x:Math.cos(i*Math.PI/6)*130,y:Math.sin(i*Math.PI/6)*110-20,rotate:i*65,scale:[0,1,1,.5]}} transition={{duration:duration===0?0:1,delay:duration===0?0:i*.025}}/>) }<motion.div className="completion-medal" initial={{scale:.7,rotate:-15}} animate={{scale:1,rotate:0}} transition={{type:'spring',bounce:.4,duration:duration===0?0:.7}}><Check size={43}/></motion.div></div><p className="eyebrow">A SMALL STEP WORTH CELEBRATING</p><h3>Look at you, <span className="serif">learning.</span></h3><p>You’ve completed <strong>{lesson.title}</strong><br/>That’s one more moment you can handle in English.</p><div className="completion-stats"><span><strong>{explored.length}</strong>words explored</span><span><strong>{score}/3</strong>quiz answers</span><span><strong>{correct?'✓':'↻'}</strong>sentence practice</span></div><button className="button dark" onClick={onNext||close}>{onNext?'Keep the good thing going':'Back to your lessons'}<ArrowRight size={18}/></button><button className="reset-link review-lesson" onClick={()=>go(0)}>Revisit this lesson</button></div>}
 </motion.div></AnimatePresence>{message&&<p className="audio-message" role="status">{message}</p>}{step<4&&<div className="dialog-footer"><button className="reset-link" disabled={step===0} onClick={()=>go(step-1)}><ChevronLeft size={15}/> Back</button><span>{step+1} / 5</span>{step===3?<button className="reset-link" onClick={()=>go(4)}>Try speaking <ArrowRight size={15}/></button>:<button className="button dark" onClick={()=>go(step+1)}>{['Try a conversation','Build a sentence','Test your knowledge'][step]}<ArrowRight size={16}/></button>}</div>}
 </motion.section></motion.div>
}
