'use client';
import {useEffect,useState,useCallback} from 'react';
import {AnimatePresence,motion,MotionConfig} from 'framer-motion';
import {ArrowUpRight,ArrowRight,Check,Volume2,BookOpen,Headphones,MessageCircle,Sun,Moon,Pause,Play,Sparkles,Menu,X} from 'lucide-react';
import {lessons} from './lessons';
import LessonPlayer from './lesson-player';
import BeePet from './bee-pet';
import Assessment from './assessment';
import {useLanguage,LanguageSwitcher} from './i18n/provider';
export default function Home(){
 const {t,locale}=useLanguage();
 const [active,setActive]=useState<number|null>(null),[done,setDone]=useState<number[]>([]),[menu,setMenu]=useState(false),[dark,setDark]=useState(false),[paused,setPaused]=useState(false),[practice,setPractice]=useState(0),[audio,setAudio]=useState(false);
 useEffect(()=>{try{const progress=JSON.parse(localStorage.getItem('bee-progress')||'[]');if(Array.isArray(progress))setDone([...new Set(progress.filter((n:unknown)=>typeof n==='number'&&n>=0&&n<4))] as number[]);const theme=localStorage.getItem('bee-theme');const night=theme?theme==='dark':window.matchMedia('(prefers-color-scheme: dark)').matches;setDark(night);document.documentElement.dataset.theme=night?'dark':'light';setPaused(localStorage.getItem('bee-pause')==='true')}catch{}},[]);
 const changeTheme=()=>{const next=!dark;setDark(next);document.documentElement.dataset.theme=next?'dark':'light';try{localStorage.setItem('bee-theme',next?'dark':'light')}catch{}};
 const toggleMotion=()=>{const next=!paused;setPaused(next);try{localStorage.setItem('bee-pause',String(next))}catch{}};
 const close=useCallback(()=>setActive(null),[]);
 const complete=()=>{if(active===null)return;const next=[...new Set([...done,active])];setDone(next);try{localStorage.setItem('bee-progress',JSON.stringify(next))}catch{}};
 const hear=()=>{if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance('Hello! It’s lovely to meet you.');utterance.lang='en-GB';utterance.rate=.8;utterance.onend=()=>setAudio(false);utterance.onerror=()=>setAudio(false);setAudio(true);window.speechSynthesis.speak(utterance)};
 const lesson=active!==null?lessons[active]:null;
 return <MotionConfig reducedMotion="user"><div className={paused?'site-shell motion-paused':'site-shell'}><a className="skip" href="#free">{t('skip')}</a><header><a className="brand" href="#" dir="ltr" aria-label="BeeLikeNative"><span className="brandmark">b<span>✦</span></span>bee<span className="brand-light">like</span>native<span className="brand-dot">.</span></a><nav className={menu?'show':''}><a href="#approach" onClick={()=>setMenu(false)}>{t('navApproach')}</a><a href="#free" onClick={()=>setMenu(false)}>{t('navLessons')}</a><a href="#level" onClick={()=>setMenu(false)}>{t('navLevel')}</a></nav><LanguageSwitcher/><div className="site-controls"><button onClick={toggleMotion} aria-label={paused?t('resume'):t('pause')} aria-pressed={paused}>{paused?<Play size={17}/>:<Pause size={17}/>}</button><button onClick={changeTheme} aria-label={dark?t('light'):t('dark')}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></div><button className="menu" onClick={()=>setMenu(!menu)} aria-label={t('menu')} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></header>
 <main><section className="hero"><motion.div className="hero-copy" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.6}}><p className="eyebrow"><span className="status-dot"/>{t('heroEyebrow')}</p><h1>{t('heroTitle')}<br/><span className="serif">{t('heroAccent')}</span></h1><p className="hero-description">{t('heroBody')}</p><div className="hero-actions"><a href="#free" className="button dark">{t('start')}<ArrowUpRight size={20}/></a><a href="#level" className="hero-level-link">{t('navLevel')}<ArrowRight size={16}/></a></div><p className="micro"><Check size={15}/>{t('freeNote')}</p><a className="hero-teacher" href="#teacher"><span className="author-avatar" role="img" aria-label="BeeLikeNative"/><strong>{t('meetCreator')}<ArrowUpRight size={13}/></strong></a></motion.div>
 <motion.div className="hero-world" initial={{opacity:0,y:25,rotate:2}} animate={{opacity:1,y:0,rotate:0}} transition={{duration:.7}} dir="ltr"><div className="world-grid"/><span className="world-label">{t('courage')}</span><motion.span className="world-hello" lang="en" initial={{opacity:0,rotate:-12}} animate={{opacity:1,rotate:-6}} transition={{delay:.2,duration:.6}}>Hello!</motion.span><span className="world-star">✳</span><BeePet paused={paused} completed={done.length}/><div className="world-sticker"><span>{t('nextChapter')}</span>A1 <ArrowRight size={15}/> A2</div><div className="floating-word">{t('youCan')}<span>↗</span></div></motion.div></section>
 <div className="ticker">{(['realLife','little','pace','confidence'] as const).map(key=><span className="ticker-item" key={key}>{t(key)}<i>✳</i></span>)}</div>
 <section id="approach" className="approach-new section"><div><p className="eyebrow">{t('approachEye')}</p><h2>{t('approachTitle')}<br/><span className="serif">{t('approachAccent')}</span></h2></div><p>{t('approachBody')}</p><div className="approach-number" aria-hidden="true">01—∞</div></section>
 <section id="teacher" className="creator-studio section"><div className="studio-shell"><div className="studio-copy"><p className="eyebrow"><span className="status-dot"/>{t('teacherEye')}</p><h2>{t('teacherTitle')}<br/><span className="serif">{t('teacherAccent')}</span></h2><p>{t('teacherBody')}</p><a href="https://www.tiktok.com/@beelikenative" target="_blank" rel="noopener noreferrer" className="studio-link">{t('watch')}<ArrowUpRight size={21}/></a><div className="studio-tabs" role="tablist" aria-label={t('navApproach')}>{(['read','listen','speak'] as const).map((key,i)=><button key={key} role="tab" id={`practice-tab-${i}`} aria-selected={practice===i} aria-controls="practice-panel" tabIndex={practice===i?0:-1} onClick={()=>setPractice(i)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const n=(practice+(e.key==='ArrowRight'?1:2))%3;setPractice(n);document.getElementById(`practice-tab-${n}`)?.focus()}}}>{i===0?<BookOpen size={16}/>:i===1?<Headphones size={16}/>:<MessageCircle size={16}/>}<span>{t(key)}</span></button>)}</div><div className="studio-practice" role="tabpanel" id="practice-panel" aria-labelledby={`practice-tab-${practice}`}><p>{t((['readTip','listenTip','speakTip'] as const)[practice])}</p><div className="phrase-example" lang="en" dir="ltr">{practice===2?'Hello! My name is…':'Hello! It’s lovely to meet you.'}<button aria-label={t('hearPhrase')} onClick={hear}>{audio?<span className="sound-bars"><i/><i/><i/></span>:<Volume2 size={19}/>}</button></div><small>{t('browserVoice')}</small></div></div><div className="studio-visual" dir="ltr"><div className="studio-arch"/><motion.div className="studio-portrait" role="img" aria-label="BeeLikeNative creator" initial={{opacity:0,y:25,rotate:2}} whileInView={{opacity:1,y:0,rotate:-3}} viewport={{once:true,amount:.3}} transition={{duration:.7}}/><span className="studio-signature" lang="en">a little English,<br/><em>a little braver.</em></span><motion.div className="studio-polaroid" initial={{opacity:0,y:30,rotate:-6}} whileInView={{opacity:1,y:0,rotate:8}} viewport={{once:true}} transition={{duration:.65,delay:.1}}><div role="img" aria-label="BeeLikeNative creator with a microphone"/><span>beelikenative <span>↗</span></span></motion.div><div className="studio-seal"><span>HELLO</span><span>✳</span><span>WORLD</span></div><span className="studio-spark one">✦</span><span className="studio-spark two">✳</span><div className="studio-photo-caption"><span className="author-avatar"/><span>{t('realLife')}<strong>{t('confidence')}</strong></span></div></div></div></section>
 <Assessment/>
 <section id="free" className="lessons section"><div className="section-heading"><div><p className="eyebrow">{t('lessonsEye')}</p><div className="heading-with-pet"><h2>{t('lessonsTitle')}<br/><span className="serif">{t('lessonsAccent')}</span></h2><BeePet compact paused={paused}/></div></div><div className="lesson-intro"><p>{t('lessonsBody')}</p><span className="progress-label">{done.length} / 4 {t('completed')}<span className="progress-track"><i style={{width:`${done.length*25}%`}}/></span></span></div></div><div className="lesson-grid">{lessons.map((l,i)=><motion.button initial={{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.45,delay:i*.05}} whileHover={{y:-8,rotate:i%2?1:-1}} whileTap={{scale:.97}} className={`lesson-card ${l.color}`} key={l.title} onClick={()=>setActive(i)}><div className="card-top"><span>{t('lesson')} 0{i+1}</span><span>{done.includes(i)?<Check size={18}/>:l.time}</span></div><span className="lesson-illustration">{l.icon}</span><h3 lang="en" dir="ltr">{l.title}</h3><p lang="en" dir="ltr">{l.topic}</p><div className="card-bottom"><span>{done.includes(i)?t('again'):t('begin')}</span><span className="round-arrow"><ArrowUpRight size={20}/></span></div></motion.button>)}</div><p className="lesson-note"><Sparkles size={16}/>{t('lessonNote')}</p></section>
 <section id="next" className="section next-section"><div><p className="eyebrow">{t('nextEye')}</p><h2>{t('nextTitle')}</h2><a className="text-link" href="#level">{t('navLevel')}<ArrowUpRight size={17}/></a></div><div className="next-options"><article className="bridge"><span className="tag">{t('upcoming')}</span><h3 lang="en">The A2 Bridge</h3><p>{t('bridgeBody')}</p><a href="mailto:hello@beelikenative.com?subject=A2%20Bridge%20updates" className="text-link">{t('askCourse')}<ArrowUpRight size={17}/></a></article><article className="private"><span className="tag">{t('nextEye')}</span><h3>{t('privateTitle')}</h3><p>{t('privateBody')}</p><a href="mailto:hello@beelikenative.com?subject=Private%20lessons" className="button dark">{t('contact')}<ArrowUpRight size={19}/></a></article></div></section>
 <section className="faq section"><h2>{t('faqTitle')}</h2>{([['faq1','faq1a'],['faq2','faq2a'],['faq3','faq3a']] as const).map(([q,a])=><details key={q}><summary>{t(q)}<span>+</span></summary><p>{t(a)}</p></details>)}</section>
 <section className="final-cta"><span>{t('nextEye')}</span><h2>{t('youCan')} <span className="wave">👋</span></h2><a href="#free" className="button dark">{t('start')}<ArrowUpRight size={20}/></a></section></main><footer><a className="brand" href="#" dir="ltr">beelikenative.</a><p>{t('footer')}</p><a href="mailto:hello@beelikenative.com">{t('contact')}<ArrowUpRight size={15}/></a><small>© {new Date().getFullYear()} BeeLikeNative · {t('independent')}</small></footer>
 <AnimatePresence>{lesson&&active!==null&&<LessonPlayer paused={paused} key={`${active}-${locale}`} lesson={lesson} index={active} close={close} onComplete={complete} onNext={active<3?()=>setActive(active+1):undefined}/>}</AnimatePresence></div></MotionConfig>
}
