'use client';
import {useEffect,useState,useCallback} from 'react';
import {AnimatePresence,motion,MotionConfig} from 'framer-motion';
import {ArrowUpRight,ArrowRight,Check,Volume2,BookOpen,Headphones,MessageCircle,ChevronRight,Sun,Moon,Pause,Play,Sparkles,Menu,X} from 'lucide-react';
import {lessons} from './lessons';
import LessonPlayer from './lesson-player';
import BeePet from './bee-pet';

export default function Home(){
 const [active,setActive]=useState<number|null>(null),[done,setDone]=useState<number[]>([]),[menu,setMenu]=useState(false),[audioMessage,setAudioMessage]=useState(''),[dark,setDark]=useState(false),[paused,setPaused]=useState(false);
 useEffect(()=>{try{const progress=JSON.parse(localStorage.getItem('bee-progress')||'[]');if(Array.isArray(progress))setDone(progress.filter((n:unknown)=>typeof n==='number'&&n>=0&&n<4));const theme=localStorage.getItem('bee-theme');const night=theme?theme==='dark':window.matchMedia('(prefers-color-scheme: dark)').matches;setDark(night);document.documentElement.dataset.theme=night?'dark':'light';setPaused(localStorage.getItem('bee-pause')==='true')}catch{}},[]);
 const changeTheme=()=>{const next=!dark;setDark(next);document.documentElement.dataset.theme=next?'dark':'light';try{localStorage.setItem('bee-theme',next?'dark':'light')}catch{}};
 const toggleMotion=()=>{const next=!paused;setPaused(next);try{localStorage.setItem('bee-pause',String(next))}catch{}};
 const close=useCallback(()=>setActive(null),[]);
 const open=(i:number)=>setActive(i);
 const complete=()=>{if(active===null)return;const next=[...new Set([...done,active])];setDone(next);try{localStorage.setItem('bee-progress',JSON.stringify(next))}catch{}};
 const speak=(s:string)=>{if(!('speechSynthesis' in window)){setAudioMessage('Audio is unavailable in this browser. Read the conversation aloud to practise.');return}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(s);utterance.lang='en-GB';utterance.rate=.8;window.speechSynthesis.speak(utterance);setAudioMessage('Listening practice uses your browser’s English voice.')};
 const lesson=active!==null?lessons[active]:null;
 return <MotionConfig reducedMotion="user"><div className={paused?"site-shell motion-paused":"site-shell"}><a className="skip" href="#free">Skip to free lessons</a><header><a className="brand" href="#"><span className="brandmark">b<span>✦</span></span>bee<span className="brand-light">like</span>native<span className="brand-dot">.</span></a><nav className={menu?'show':''}><a href="#approach" onClick={()=>setMenu(false)}>Our approach</a><a href="#free" onClick={()=>setMenu(false)}>Free lessons</a><a href="#next" onClick={()=>setMenu(false)}>Go further</a></nav><div className="site-controls"><button onClick={toggleMotion} aria-label={paused?"Resume mascot motion":"Pause mascot motion"} aria-pressed={paused} title={paused?"Resume mascot motion":"Pause mascot motion"}>{paused?<Play size={17}/>:<Pause size={17}/>}</button><button onClick={changeTheme} aria-label={dark?"Switch to light theme":"Switch to dark theme"} title={dark?"Switch to light theme":"Switch to dark theme"}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></div><a className="nav-cta" href="#free">Let’s learn <ArrowUpRight size={16}/></a><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></header>
 <main><section className="hero"><motion.div className="hero-copy" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.6}}><p className="eyebrow"><span className="status-dot"/> A LITTLE ENGLISH. A BIG NEW WORLD.</p><h1>Small lessons.<br/>Real <span className="serif">conversations.</span></h1><p className="hero-description">English opens doors. Let’s open yours.<br/>Build the confidence to speak, one everyday moment at a time.</p><a href="#free" className="button dark">Find your first words <ArrowUpRight size={20}/></a><p className="micro"><Check size={15}/> Four free A1 lessons <span>·</span> No sign-up needed</p><a className="hero-teacher" href="#teacher"><span className="author-avatar" role="img" aria-label="BeeLikeNative creator"/><span>A real teacher. A friendly place to start.<strong>Meet the voice behind BeeLikeNative <ArrowUpRight size={13}/></strong></span></a></motion.div>
 <motion.div className="hero-world" initial={{opacity:0,y:25,rotate:2}} animate={{opacity:1,y:0,rotate:0}} transition={{duration:.7}}><div className="world-grid"/><span className="world-label">A LITTLE COURAGE GOES A LONG WAY</span><motion.span className="world-hello" initial={{opacity:0,rotate:-12}} animate={{opacity:1,rotate:-6}} transition={{delay:.2,duration:.6}}>Hello!</motion.span><span className="world-star">✳</span><BeePet paused={paused} completed={done.length}/><div className="world-sticker"><span>YOUR NEXT CHAPTER</span>A1 <ArrowRight size={15}/> A2</div><div className="floating-word">You’ve got this. <span>↗</span></div></motion.div></section>
 <div className="ticker"><span>Made for real life</span><span>✳</span><span>Little by little</span><span>✳</span><span>At your own pace</span><span>✳</span><span>Say it with confidence</span><span>✳</span></div>
 <section id="approach" className="approach section"><div><p className="eyebrow">LESS PRESSURE. MORE PROGRESS.</p><h2>You don’t need perfect English.<br/>You need a <span className="serif">place to start.</span></h2></div><div className="approach-copy"><p>A new language can feel like a big leap. We make it a series of small, doable steps—with useful words and practice you can use today.</p><div className="features"><span><BookOpen/> Learn a little</span><span><Headphones/> Listen closely</span><span><MessageCircle/> Try it out loud</span></div></div></section>
 <motion.section id="teacher" className="teacher-section section" initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.65}}><div className="teacher-photo-composition"><div className="teacher-photo" role="img" aria-label="The BeeLikeNative creator teaching English"/><div className="teacher-photo-small" role="img" aria-label="BeeLikeNative creator with her microphone"/><span className="photo-stamp">REAL WORDS.<br/>REAL CONNECTION.</span><span className="photo-star">✳</span></div><div className="teacher-story"><p className="eyebrow">MEET THE VOICE BEHIND BEELIKENATIVE</p><h2>A familiar face.<br/>A <span className="serif">fresh confidence.</span></h2><p>Meet the creator behind BeeLikeNative’s English videos. Her short, everyday conversations give you a chance to listen, repeat, and find your own voice.</p><p>Explore the interactive starter here, then visit her channel for more speaking practice.</p><a href="https://www.tiktok.com/@beelikenative" target="_blank" rel="noopener noreferrer" className="button dark">Meet her on TikTok <ArrowUpRight size={18}/></a><div className="teacher-caption"><MessageCircle size={18}/><span>A little practice. A more confident you.</span></div></div></motion.section>
 <section id="free" className="lessons section"><div className="section-heading"><div><p className="eyebrow">THE FREE A1 STARTER</p><div className="heading-with-pet"><h2>Your first words.<br/><span className="serif">Your next adventure.</span></h2><BeePet compact paused={paused}/></div></div><div className="lesson-intro"><p>Four small lessons. Four everyday moments.<br/>Start anywhere. Come back anytime.</p><span className="progress-label">{done.length} / 4 lessons complete <span className="progress-track"><i style={{width:`${done.length*25}%`}}/></span></span></div></div><div className="lesson-grid">{lessons.map((l,i)=><motion.button initial={{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.45,delay:i*.05}} whileHover={{y:-8,rotate:i%2?1:-1}} whileTap={{scale:.97}} className={`lesson-card ${l.color}`} key={l.title} onClick={()=>open(i)}><div className="card-top"><span>LESSON 0{i+1}</span><span>{done.includes(i)?<Check size={18}/>:l.time}</span></div><span className="lesson-illustration">{l.icon}</span><h3>{l.title}</h3><p>{l.topic}</p><div className="card-bottom"><span>{done.includes(i)?'Practise again':'Let’s do this'}</span><span className="round-arrow"><ArrowUpRight size={20}/></span></div></motion.button>)}</div><p className="lesson-note"><Sparkles size={16}/> A little reading, a little listening, and a chance to try. All free.</p></section>
 <section className="quote-section"><span className="quote-star">✳</span><p>From “I know the words”<br/>to <span className="serif">“I can say it.”</span></p><span className="quote-small">THAT’S THE MOMENT WE’RE HERE FOR.</span></section>
 <section id="next" className="section next-section"><div><p className="eyebrow">WHEN YOU’RE READY FOR MORE</p><h2>A small start.<br/>A <span className="serif">bigger possibility.</span></h2><p className="next-copy">Find your rhythm with the free lessons. Then choose the support that fits your next step.</p></div><div className="next-options"><article className="bridge"><span className="tag">IN THE MAKING</span><h3>The A2 Bridge</h3><p>A planned 30-day course to help you build on the basics, with everyday topics and a clear path forward.</p><ul><li><Check/> Short video lessons</li><li><Check/> Printable practice & vocabulary</li><li><Check/> Weekly progress checks</li></ul><a href="mailto:hello@beelikenative.com?subject=A2%20Bridge%20updates" className="text-link">Ask about the upcoming course <ArrowUpRight size={17}/></a></article><article className="private"><span className="tag">A LITTLE PERSONAL SUPPORT</span><h3>Your goals. Your lessons.</h3><p>Want to practise with a teacher? Ask about private lessons built around your English and your everyday life.</p><a href="mailto:hello@beelikenative.com?subject=Private%20lessons" className="button dark">Let’s talk <ArrowUpRight size={19}/></a></article></div></section>
 <section className="faq section"><p className="eyebrow">GOOD QUESTIONS</p><h2>A little clarity.</h2>{[['Is this right for my level?','The free lessons are for A1 beginners. You’ll practise simple introductions, daily routines, ordering in a café, and describing places. If you already know the basics, use them as a quick refresh.'],['Are the starter lessons really free?','Yes. Open any lesson and start learning. There is no account, payment, or email address required.'],['Will I reach A2 after four lessons?','Four lessons are a starting point, not a full A2 qualification. Regular practice across reading, listening, writing, and speaking will help you build toward A2.'],['Can I learn on my phone?','Yes. The lessons work on phones, tablets, and computers. Your completed lessons are saved in this browser, so use the same device to see your progress.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section>
 <section className="final-cta"><span>YOUR NEXT STEP DOESN’T HAVE TO BE BIG.</span><h2>Just say <span className="serif">hello.</span> <span className="wave">👋</span></h2><a href="#free" className="button dark">Start learning for free <ArrowUpRight size={20}/></a></section></main><footer><a className="brand" href="#">beelikenative.</a><p>Little lessons. More possibilities.</p><a href="mailto:hello@beelikenative.com">Say hello <ArrowUpRight size={15}/></a><small>© {new Date().getFullYear()} BeeLikeNative · Independent redesign</small></footer>
 <AnimatePresence>{lesson&&active!==null&&<LessonPlayer paused={paused} key={active} lesson={lesson} index={active} close={close} onComplete={complete} onNext={active<3?()=>setActive(active+1):undefined}/>}</AnimatePresence></div></MotionConfig>
}
